[package]
name = "dawrs"
version = "0.1.0"
authors = ["XBagon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.11"
anyhow = "1.0"
plotters = "0.2"
shrinkwraprs = "0.3"
serde = "1.0"
rand = "0.7"